### ISSUE TITLE
Cannot find library NSMedieval

### ISSUE THREAD

**Issue by xamroot** [benjaminfoo/GoingMedievalModLauncher#1]
Hey just wondering how to get this library? Didn't see it mentioned in the readme. Many of the c# files are using it so I need it to try developing mods. Thanks!

**Comment by benjaminfoo** [comment]
Hey xamroot, 
you need to setup the required assemblies (dlls) which can be found at: 
<Your_Steam_Directory>steam\steamapps\common\Going Medieval\Going 

I've updated the wiki with all the instructions that are needed: 
https://github.com/benjaminfoo/GoingMedievalModLauncher/wiki/Loader-Development

**Comment by xamroot** [comment]
Awesome ty
